TicketApplication/Controllers/audit/CreateAdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketApplication.Core;
using TicketApplication.Library;
using TicketApplication.Model;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TicketApplication.Controllers.audit
{
    public class CreateAdminUserController : Controller
    {

        IRegistration _IRepository;
        IRoles _IRoles;
        public CreateAdminUserController(IRegistration IRepository, IRoles IRoles)
        {
            _IRepository = IRepository;
            _IRoles = IRoles;
        }


        [HttpGet]
        public IActionResult Create()
        {
            Registration Registration = new Registration();
            return View(Registration);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Registration Registration)
        {
            try
            {
                var isUsernameExists = _IRepository.CheckUserNameExists(Registration.Username);

                if (isUsernameExists)
                {
                    ModelState.AddModelError("", errorMessage: "Username Already Used try unique one!");
                }
                else
                {
                    Registration.CreatedOn = DateTime.Now;
                    Registration.RoleID = _IRoles.getRolesofUserbyRolename("Admin");
                    Registration.Password = EncryptionLibrary.EncryptText(Registration.Password);
                    Registration.ConfirmPassword = EncryptionLibrary.EncryptText(Registration.ConfirmPassword);
                    if (_IRepository.AddUser(Registration) > 0)
                    {
                        TempData["MessageRegistration"] = "Data Saved Successfully!";
                        return View(Registration);
                    }
                    else
                    {
                        return View(Registration);
                    }
                }

                return View(Registration);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public JsonResult CheckUserNameExists(string Username)
        {
            try
            {
                var isUsernameExists = _IRepository.CheckUserNameExists(Username);
                if (isUsernameExists)
                {
                    return Json(data: true);
                }
                else
                {
                    return Json(data: false);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

TicketApplication/Views/CreateAdminUser/Create.cshtml
@model TicketApplication.Model.Registration
@{
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}
<div class="container">
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Register</div>
        <div class="panel-body">

            @if (TempData["MessageRegistration"] != null)
            {
                <p class="alert alert-success" id="successMessage">@TempData["MessageRegistration"]</p>
            }

            <form method="post" asp-controller="CreateAdminUser" asp-action="Create">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="row">
                    <div class="col-lg-4">
                        <label class="control-label" asp-for="Name">Name</label>
                        <input asp-for="Name" type="text" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-lg-4">
                        <label class="control-label" asp-for="EmailID">Email</label>
                        <input asp-for="EmailID" type="text" class="form-control" />
                        <span asp-validation-for="EmailID" class="text-danger"></span>
                    </div>

                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <label class="control-label" asp-for="Username">Username</label>
                        <input asp-for="Username" onblur="CheckUsernameExists();" type="text" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="col-lg-4">
                        <label class="control-label" asp-for="Password">Password</label>
                        <input asp-for="Password" type="password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="col-lg-4">
                        <label class="control-label" asp-for="ConfirmPassword">ConfirmPassword</label>
                        <input asp-for="ConfirmPassword" type="password" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <br />
                        <input id="Submit1" type="submit" class="btn btn-primary" value="Register" />
                        <a class="btn btn-success" href="/CreateAdminUser/Create">Clear</a>
                    </div>


                </div>
            </form>


        </div>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function ()
    {
       




</script>

<script type="text/javascript">

    $(document).ready(function ()
    {
   

    function OnlyNumeric(evt)
    {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if ((charCode < 48 || charCode > 57))
        {
            if (charCode == 8 || charCode == 46 || charCode == 0)
            {
                return true;
            }
            else {
                return false;
            }
        }
    }

    function CheckUsernameExists()
    {
        var url = '@Url.Content("~/")' + "CreateAdminUser/CheckUserNameExists";
        var source = "#Username";
        $.post(url, { Username: $(source).val() }, function (data)
                {
                    if (data)
                    {
                        $(source).val('');
                        alert("Username Already Used try unique one!");
                    }
                    else
                    {

                    }
                });
        }
    });
</script>